CREATE DATABASE BIBLIOTECA_LEONARDO;
USE BIBLIOTECA_LEONARDO;

/* Lógico_1: */
CREATE TABLE LIVRO (
    isbn VARCHAR(50) PRIMARY KEY,
    titulo VARCHAR(100),
    ano int,
    FK_EDITORA_Id INT,
    FK_CATEGORIA_codigo INT
);

CREATE TABLE AUTOR (
    Id INT PRIMARY KEY IDENTITY,
    nome VARCHAR(100),
    nacionalidade VARCHAR(50)
);

CREATE TABLE CATEGORIA (
    codigo INT PRIMARY KEY IDENTITY,
    descricao VARCHAR(50)
);

CREATE TABLE EDITORA (
    Id INT PRIMARY KEY IDENTITY,
    nome VARCHAR(100)
);

CREATE TABLE LIVRO_AUTOR_ESCRITO (
    FK_LIVRO_isbn VARCHAR(50),
    FK_AUTOR_Id INT
);
 
ALTER TABLE LIVRO ADD CONSTRAINT FK_LIVRO_2
    FOREIGN KEY (FK_EDITORA_Id)
    REFERENCES EDITORA (Id)
    ON DELETE CASCADE;
 
ALTER TABLE LIVRO ADD CONSTRAINT FK_LIVRO_3
    FOREIGN KEY (FK_CATEGORIA_codigo)
    REFERENCES CATEGORIA (codigo)
    ON DELETE CASCADE;
 
ALTER TABLE LIVRO_AUTOR_ESCRITO ADD CONSTRAINT FK_LIVRO_AUTOR_ESCRITO_1
    FOREIGN KEY (FK_LIVRO_isbn)
    REFERENCES LIVRO (isbn);
 
ALTER TABLE LIVRO_AUTOR_ESCRITO ADD CONSTRAINT FK_LIVRO_AUTOR_ESCRITO_2
    FOREIGN KEY (FK_AUTOR_Id)
    REFERENCES AUTOR (Id);



INSERT INTO Autor (Nome, Nacionalidade) VALUES ('J.K. Rowling', 'Inglaterra');
INSERT INTO Autor (Nome, Nacionalidade) VALUES ('Clive Staples Lewis', 'Inglaterra');
INSERT INTO Autor (Nome, Nacionalidade) VALUES ('Affonso Solano', 'Brasil');
INSERT INTO Autor (Nome, Nacionalidade) VALUES ('Marcos Piangers', 'Brasil');
INSERT INTO Autor (Nome, Nacionalidade) VALUES ('Tiririca', 'Brasil');
INSERT INTO Autor (Nome, Nacionalidade) VALUES ('Bianca Mól', 'Brasil');


SELECT A.Nome, A.Nacionalidade
FROM Autor AS A
WHERE A.Nome LIKE '%anc%';


INSERT INTO Categoria (descricao) VALUES ('Literatura Juvenil'); 
INSERT INTO Categoria (descricao) VALUES ('Ficção Científica');  
INSERT INTO Categoria (descricao) VALUES ('Humor');  





INSERT INTO Editora (nome) VALUES ('Rocco');              
INSERT INTO Editora (nome) VALUES ('Wmf Martins Fontes');  
INSERT INTO Editora (nome) VALUES ('Casa da Palavra');    
INSERT INTO Editora (nome) VALUES ('Belas Letras');        
INSERT INTO Editora (nome) VALUES ('Matrix');         




INSERT INTO Livro (isbn, titulo, ano, FK_EDITORA_Id, FK_CATEGORIA_codigo) 
VALUES ('8532511015', 'Harry Potter e A Pedra Filosofal', 2000, 1, 1);

INSERT INTO Livro (isbn, titulo, ano, FK_EDITORA_Id, FK_CATEGORIA_codigo) 
VALUES ('9788578270698', 'As Crônicas de Nárnia', 2009, 2, 1);

INSERT INTO Livro (isbn, titulo, ano, FK_EDITORA_Id, FK_CATEGORIA_codigo) 
VALUES ('9788577343348', 'O Espadachim de Carvão', 2013, 3, 2);

INSERT INTO Livro (isbn, titulo, ano, FK_EDITORA_Id, FK_CATEGORIA_codigo) 
VALUES ('9788581742458', 'O Papai É Pop', 2015, 4, 3);

INSERT INTO Livro (isbn, titulo, ano, FK_EDITORA_Id, FK_CATEGORIA_codigo) 
VALUES ('9788582302026', 'Pior Que Tá Não Fica', 2015, 5, 3);

INSERT INTO Livro (isbn, titulo, ano, FK_EDITORA_Id, FK_CATEGORIA_codigo) 
VALUES ('9788577345670', 'Garota Desdobrável', 2015, 3, 1);

INSERT INTO Livro (isbn, titulo, ano, FK_EDITORA_Id, FK_CATEGORIA_codigo) 
VALUES ('8532512062', 'Harry Potter e o prisioneiro de Azkaban', 2000, 1, 1);


INSERT INTO LIVRO_AUTOR_ESCRITO (FK_LIVRO_isbn, FK_AUTOR_Id) VALUES ('8532511015', 1);
INSERT INTO LIVRO_AUTOR_ESCRITO (FK_LIVRO_isbn, FK_AUTOR_Id) VALUES ('9788578270698', 2);
INSERT INTO LIVRO_AUTOR_ESCRITO (FK_LIVRO_isbn, FK_AUTOR_Id) VALUES ('9788577343348', 3);
INSERT INTO LIVRO_AUTOR_ESCRITO (FK_LIVRO_isbn, FK_AUTOR_Id) VALUES ('9788581742458', 4);
INSERT INTO LIVRO_AUTOR_ESCRITO (FK_LIVRO_isbn, FK_AUTOR_Id) VALUES ('9788582302026', 5);
INSERT INTO LIVRO_AUTOR_ESCRITO (FK_LIVRO_isbn, FK_AUTOR_Id) VALUES ('9788577345670', 6);
INSERT INTO LIVRO_AUTOR_ESCRITO (FK_LIVRO_isbn, FK_AUTOR_Id) VALUES ('8532512062', 1);



--QUESTAO 7)
SELECT L.isbn, L.titulo, L.ano
FROM LIVRO AS L
ORDER BY L.titulo;

SELECT L.isbn, L.titulo, L.ano
FROM LIVRO AS L
ORDER BY L.titulo;

--QUESTAO 8)
SELECT  AUTOR.nome ,LIVRO.titulo
FROM LIVRO, AUTOR, LIVRO_AUTOR_ESCRITO
WHERE LIVRO_AUTOR_ESCRITO.FK_LIVRO_isbn = LIVRO.isbn AND 
LIVRO_AUTOR_ESCRITO.FK_AUTOR_Id = AUTOR.id order by AUTOR.Nome;

--QUESTAO 8) COM INNER JOIN
SELECT  AUTOR.nome ,LIVRO.titulo
FROM LIVRO
INNER JOIN LIVRO_AUTOR_ESCRITO ON LIVRO_AUTOR_ESCRITO.FK_LIVRO_isbn = LIVRO.isbn
INNER JOIN AUTOR ON AUTOR.Id = LIVRO_AUTOR_ESCRITO.FK_AUTOR_Id
order by AUTOR.Nome;


--QUESTAO 9)
SELECT LIVRO.titulo AS 'TITULO DOS LIVROS' , LIVRO.ano AS 'ANO ORDENADO', CATEGORIA.descricao AS 'CATEGORIAS'
FROM LIVRO , CATEGORIA
WHERE LIVRO.FK_CATEGORIA_codigo = CATEGORIA.codigo AND
CATEGORIA.descricao = 'Literatura Juvenil' order by LIVRO.ano;


--QUESTAO 9) COM INNER JOIN
SELECT LIVRO.titulo AS 'TITULO DOS LIVROS' , LIVRO.ano AS 'ANO ORDENADO', CATEGORIA.descricao AS 'CATEGORIAS'
FROM LIVRO 
INNER JOIN CATEGORIA ON CATEGORIA.codigo = LIVRO.FK_CATEGORIA_codigo
WHERE CATEGORIA.descricao = 'Literatura Juvenil' order by LIVRO.ano;


--QUESTAO 10)
SELECT LIVRO.titulo AS 'TITULO DOS LIVROS', LIVRO.ano AS 'ANO ORDENADO', CATEGORIA.descricao AS 'CATEGORIAS'
FROM LIVRO, CATEGORIA
WHERE LIVRO.FK_CATEGORIA_codigo = CATEGORIA.codigo 
  AND (CATEGORIA.descricao = 'Humor' OR  CATEGORIA.descricao = 'Ficção Científica')
  AND LIVRO.ano BETWEEN 2000 AND 2015
ORDER BY LIVRO.ano;

--QUESTAO 10) COM INNER JOIN
SELECT LIVRO.titulo AS 'TITULO DOS LIVROS', LIVRO.ano AS 'ANO ORDENADO', CATEGORIA.descricao AS 'CATEGORIAS'
FROM LIVRO
INNER JOIN CATEGORIA ON CATEGORIA.codigo = LIVRO.FK_CATEGORIA_codigo
WHERE (CATEGORIA.descricao = 'Humor' OR  CATEGORIA.descricao = 'Ficção Científica')
  AND LIVRO.ano BETWEEN 2000 AND 2015
ORDER BY LIVRO.ano;




