USE EMPRESA;
GO

-- 1 )
DELETE FROM DEPARTAMENTO WHERE Dnumero >= 90;

INSERT INTO DEPARTAMENTO (Dnome, Dnumero)
VALUES ('Teste_Autocommit', 90);

BEGIN TRANSACTION;
INSERT INTO DEPARTAMENTO (Dnome, Dnumero)
VALUES ('Teste_Transacao', 91);
ROLLBACK TRANSACTION;

SELECT * FROM DEPARTAMENTO WHERE Dnumero >= 90;



-- 2 )
DELETE FROM DEPARTAMENTO WHERE Dnumero >= 92;

BEGIN TRANSACTION;
INSERT INTO DEPARTAMENTO (Dnome, Dnumero)
VALUES ('Financeiro', 92);
SAVE TRANSACTION Ponto1;
INSERT INTO DEPARTAMENTO (Dnome, Dnumero)
VALUES ('Juridico', 93);
ROLLBACK TRANSACTION Ponto1;
COMMIT TRANSACTION;

SELECT * FROM DEPARTAMENTO WHERE Dnumero >= 92;



-- 3 )
SELECT Pnome, Unome, Endereco
FROM FUNCIONARIO
WHERE Cpf = '98765432100';

BEGIN TRANSACTION;
UPDATE FUNCIONARIO
SET Endereco = 'Rua Nova, 123 - São Paulo, SP'
WHERE Cpf = '98765432100';
SELECT Pnome, Unome, Endereco
FROM FUNCIONARIO
WHERE Cpf = '98765432100';
COMMIT TRANSACTION;

SELECT Pnome, Unome, Endereco
FROM FUNCIONARIO
WHERE Cpf = '98765432100';
