
--Criação da tabela FUNCIONARIO
CREATE TABLE FUNCIONARIO (
	Pnome VARCHAR(15) NOT NULL,
    Minicial CHAR,
    Unome VARCHAR(15) NOT NULL,
    Cpf CHAR(11),
    Datanasc DATE,
    Endereco VARCHAR(255),
    Sexo CHAR,
    Salario DECIMAL(10,2),
    Cpf_supervisor CHAR(11),
    Dnr INT,
    PRIMARY KEY (Cpf),
    FOREIGN KEY (Cpf_supervisor) REFERENCES FUNCIONARIO(Cpf)
);
GO

--Tablea de DEPARTAMENTO
CREATE TABLE DEPARTAMENTO (
	Dnome VARCHAR(15) NOT NULL,
    Dnumero INT,
    Cpf_gerente CHAR(11),
    Data_inicio_gerente DATE,
    PRIMARY KEY (Dnumero),
    UNIQUE (Dnome),
    FOREIGN KEY (Cpf_gerente) REFERENCES FUNCIONARIO(CPF)
);

--Adiconando restição referencial em FUNCIONARO de DEPARTAMENTO
--Criando uma ALTERAÇÃO de Tabela
ALTER TABLE FUNCIONARIO
ADD CONSTRAINT Dnr
FOREIGN KEY (Dnr) REFERENCES DEPARTAMENTO (Dnumero);

--Criação da tabela de LOCALIZACAO_DEP
CREATE TABLE LOCALIZACAO_DEP (
	Dnumero INT NOT NULL,
	Dlocal VARCHAR (15) NOT NULL,
    PRIMARY KEY (Dnumero, Dlocal),
    FOREIGN KEY (Dnumero) REFERENCES DEPARTAMENTO (Dnumero)
);

--Criacao da tabela PROJETO
CREATE TABLE PROJETO(
	Projnome VARCHAR (15) NOT NULL,
	Projnumero INT NOT NULL,
    Projlocal VARCHAR(15),
    Dnum INT,
    PRIMARY KEY (Projnumero),
    UNIQUE (Projnome),
    FOREIGN KEY (Dnum) REFERENCES DEPARTAMENTO (Dnumero)
);

--Criação da tabela TRABALHA_EM
CREATE TABLE TRABALHA_EM(
	Fcpf CHAR(11) NOT NULL,
    Pnr INT NOT NULL,
    Horas DECIMAL (3,1) NOT NULL,
    PRIMARy KEY (Fcpf, Pnr),
    FOREIGN KEY (Fcpf) REFERENCES FUNCIONARIO (Cpf),
    FOREIGN KEY (Pnr) REFERENCES PROJETO(Projnumero)
);

--Criação da tabela DEPENDENTE sem seleção do esquema
CREATE TABLE DEPENDENTE(
	Fcpf CHAR(11) NOT NULL,
    Nome_dependente VARCHAR(15) NOT NULL,
    Sexo CHAR,
    Datanasc DATE,
    Parentesco VARCHAR(8),
    PRIMARY KEY (Fcpf, Nome_dependente),
    FOREIGN KEY (Fcpf) REFERENCES FUNCIONARIO(Cpf)
);

--Inserindo valores no Departamento
INSERT INTO DEPARTAMENTO (Dnome, Dnumero) VALUES('Pesquisa', 5);
INSERT INTO DEPARTAMENTO (Dnome, Dnumero) VALUES('Administração', 4);
INSERT INTO DEPARTAMENTO (Dnome, Dnumero) VALUES('Matriz', 1);
SELECT * FROM DEPARTAMENTO;

--Inserindo funcionarios com cargo de gerencia DATE AAAA-MM-DD
INSERT INTO FUNCIONARIO VALUES ( 'Jorge', 'E', 'Brito', '88866555576', '1937-11-10', 'Rua do Horto, 35, São Paulo, SP', 'M', 55000, NULL , 1 );
INSERT INTO FUNCIONARIO VALUES ( 'Jennifer', 'S', 'Souza', '98765432168', '1941-06-20', 'Av Arthur de Lima, 54, Santo André, SP', 'F', 43000, '88866555576' , 4 );
INSERT INTO FUNCIONARIO VALUES ( 'Fernando', 'T', 'Wong', '33344555587', '1955-12-08', 'Rua da Lapa, 34, São Paulo, SP', 'M', 40000, '88866555576' , 5 );
INSERT INTO FUNCIONARIO VALUES ( 'João', 'B', 'Silva', '12345678966', '1965-01-09', 'Rua das Flores, 751, São Paulo, SP', 'M', 30000, '33344555587' , 5 );
INSERT INTO FUNCIONARIO VALUES ( 'Alice', 'J', 'Zelaya', '99988777767', '1968-01-19', 'Rua Souza Lima, 35, Curitiba, PR', 'F', 25000, '98765432168' , 4 );
INSERT INTO FUNCIONARIO VALUES ( 'Ronaldo', 'K', 'Lima', '66688444476', '1962-09-15', 'Rua Rebouças, 65, Piracicaba, SP', 'M', 38000, '33344555587' , 5 );
INSERT INTO FUNCIONARIO VALUES ( 'Joice', 'A', 'Leite', '45345345376', '1972-07-31', 'Av. Lucas Obes, 74, São Paulo, SP', 'F', 25000, '33344555587' , 5 );
INSERT INTO FUNCIONARIO VALUES ( 'André', 'E', 'Brito', '98798798733', '1969-03-29', 'Rua Timbira, 35, São Paulo, SP', 'M', 25000, '98765432168' , 4 );

--Corrigindo erro de inserção
UPDATE FUNCIONARIO
SET Endereco = 'Rua Reboucas, 65, Piracicaba, SP'
WHERE Cpf = '66688444476';

--Recupera todas as informações de funcionários
SELECT * FROM FUNCIONARIO;

--Finzalindo o preenchimento da tabela DEPTARTAMENTO
UPDATE DEPARTAMENTO
SET Cpf_gerente = '33344555587', Data_inicio_gerente = '1988-05-22'
WHERE Dnumero = 5;
UPDATE DEPARTAMENTO
SET Cpf_gerente = '98765432168', Data_inicio_gerente = '1995-01-01'
WHERE Dnumero = 4;
UPDATE DEPARTAMENTO
SET Cpf_gerente = '88866555576', Data_inicio_gerente = '1981-06-19'
WHERE Dnumero = 1;
--Recuperar todas as informações de departamento
SELECT * FROM DEPARTAMENTO;

--Prrencher a tabela LOCALIZACAO_DEP
INSERT INTO LOCALIZACAO_DEP VALUES (1, 'São Paulo');
INSERT INTO LOCALIZACAO_DEP VALUES (4, 'Mauá');
INSERT INTO LOCALIZACAO_DEP VALUES (5, 'Santo André');
INSERT INTO LOCALIZACAO_DEP VALUES (5, 'Itu');
INSERT INTO LOCALIZACAO_DEP VALUES (5, 'São Paulo');
--Recuperando informações de LOCALIZACAO_DEP
SELECT * FROM LOCALIZACAO_DEP;

--Preenchendo a table PROJETO
INSERT INTO PROJETO VALUES ('ProdutoX', 1, 'Santo André', 5);
INSERT INTO PROJETO VALUES ('ProdutoY', 2, 'Itu', 5);
INSERT INTO PROJETO VALUES ('ProdutoZ', 3, 'São Paulo', 5);
INSERT INTO PROJETO VALUES ('Informatização', 10, 'Mauá', 4);
INSERT INTO PROJETO VALUES ('Reorganização', 20, 'São Paulo', 1);
INSERT INTO PROJETO VALUES ('Novosbenefícios', 30, 'Mauá', 4);
--Recuperando informações de PROJETO
SELECT * FROM PROJETO;

--Preenchento TRABALHA_EM
INSERT INTO TRABALHA_EM VALUES ('12345678966',1,32.5);
INSERT INTO TRABALHA_EM VALUES ('12345678966',2,7.5);
INSERT INTO TRABALHA_EM VALUES ('66688444476',3,40);
INSERT INTO TRABALHA_EM VALUES ('45345345376',1,20);
INSERT INTO TRABALHA_EM VALUES ('45345345376',2,20);
INSERT INTO TRABALHA_EM VALUES ('33344555587',2,10);
INSERT INTO TRABALHA_EM VALUES ('33344555587',3,10);
INSERT INTO TRABALHA_EM VALUES ('33344555587',10,10);
INSERT INTO TRABALHA_EM VALUES ('33344555587',20,10);
INSERT INTO TRABALHA_EM VALUES ('99988777767',10,10);
INSERT INTO TRABALHA_EM VALUES ('99988777767',30,30);
INSERT INTO TRABALHA_EM VALUES ('98798798733',10,35);
INSERT INTO TRABALHA_EM VALUES ('98798798733',30,5);
INSERT INTO TRABALHA_EM VALUES ('98765432168',30,20);
INSERT INTO TRABALHA_EM VALUES ('98765432168',20,15);

--Preenchendo a tabela de DEPENDENTES
INSERT INTO DEPENDENTE VALUES ('33344555587', 'Alicia', 'F', '1986-04-05', 'Filha');
INSERT INTO DEPENDENTE VALUES ('33344555587', 'Tiago', 'M', '1983-10-25', 'Filh0');
INSERT INTO DEPENDENTE VALUES ('33344555587', 'Janaina', 'F', '1958-05-03', 'Eposa');
INSERT INTO DEPENDENTE VALUES ('98765432168', 'Antonio', 'M', '1942-02-28', 'Marido');
INSERT INTO DEPENDENTE VALUES ('12345678966', 'Michael', 'M', '1988-01-04', 'Filho');
INSERT INTO DEPENDENTE VALUES ('12345678966', 'Alicia', 'F', '1988-12-30', 'Filha');
INSERT INTO DEPENDENTE VALUES ('12345678966', 'Elizabeth', 'F', '1967-05-05', 'Esposa');

-- Execute estes comando para a aula de IF/ELSE
-- Adicionando a coluna Bonus
ALTER TABLE FUNCIONARIO
ADD Bonus DECIMAL(10, 2) NULL;

-- Adicionando a coluna Data_Admissao
ALTER TABLE FUNCIONARIO
ADD Data_Admissao DATE NULL;

INSERT INTO FUNCIONARIO (Pnome, Minicial, Unome, Cpf, Datanasc, Endereco, Sexo, Salario, Cpf_supervisor, Dnr, Data_Admissao, Bonus)
VALUES('Carlos', 'A', 'Silva', '98765432100', '1985-04-12', 'Rua A, 123', 'M', 4500.00, NULL, 1, '2023-03-01', 1000.00),
('Ana', 'B', 'Sousa', '98765432200', '1990-06-23', 'Rua B, 456', 'F', 6500.00, '98765432100', 1, '2022-01-15', 0.00),
('Maria', 'C', 'Oliveira', '98765432300', '1978-09-17', 'Rua C, 789', 'F', 7500.00, '98765432200', 5, '2024-02-01', 1500.00),
('Paulo', 'D', 'Silva', '98765432400', '1982-11-05', 'Rua D, 101', 'M', 7000.00, '98765432300', 4, '2024-05-15', 500.00);


--Novos funcionario e departaemtneo para Aula 03
INSERT INTO FUNCIONARIO (Pnome, Minicial, Unome, Cpf, Datanasc, Endereco, Sexo, Salario, Cpf_supervisor, Dnr)
VALUES ('Carlos', 'M', 'Ferreira', '12312312311', '1980-02-15', 'Av. Paulista, 1000, São Paulo, SP', 'M', 45000, NULL, NULL),
('Mariana', 'L', 'Gomes', '32132132122', '1985-06-22', 'Rua das Acácias, 500, Rio de Janeiro, RJ', 'F', 42000, NULL, NULL),
('Pedro', 'A', 'Silva', '65465465433', '1990-11-10', 'Rua da Praia, 200, Salvador, BA', 'M', 47000, NULL, NULL);

INSERT INTO DEPARTAMENTO (Dnome, Dnumero)
VALUES ('Vendas', 6),
('RH', 7),
('TI', 8);


-- PESQUISAS DOS SLIDES --

SELECT * 
FROM FUNCIONARIO
WHERE FUNCIONARIO.Pnome like 'joão';

SELECT * 
FROM FUNCIONARIO 
WHERE funcionario.Salario <= 30000;

SELECT *
FROM FUNCIONARIO 
WHERE funcionario.Salario >= 30000 
AND FUNCIONARIO.Sexo LIKE 'M';

SELECT *
FROM FUNCIONARIO 
WHERE FUNCIONARIO.Endereco LIKE '%São Paulo%' 
OR FUNCIONARIO.Endereco LIKE '%Curitiba%';

SELECT *
FROM FUNCIONARIO 
WHERE FUNCIONARIO.Endereco NOT LIKE '%São Paulo%' 

SELECT *
FROM FUNCIONARIO 
ORDER BY FUNCIONARIO.SALARIO DESC

SELECT *
FROM FUNCIONARIO 
WHERE FUNCIONARIO.Cpf_supervisor IS NULL

SELECT *
FROM FUNCIONARIO 
WHERE FUNCIONARIO.Cpf_supervisor IS NOT NULL

SELECT TOP 3 * 
FROM FUNCIONARIO AS F
ORDER BY F.SALARIO ASC

SELECT *
FROM FUNCIONARIO 
WHERE FUNCIONARIO.Salario = (SELECT MIN(FUNCIONARIO.SALARIO)
FROM FUNCIONARIO)

SELECT *
FROM FUNCIONARIO 
WHERE FUNCIONARIO.Salario = (SELECT MAX(FUNCIONARIO.SALARIO)
FROM FUNCIONARIO)

/*
DECLARE @salario_min DECIMAL(10,2);
SELECT @salario_min = (SELECT MIN(FUNCIONARIO.SALARIO)
FROM FUNCIONARIO);

PRINT @salario_min;
SELECT *
FROM FUNCIONARIO 
WHERE FUNCIONARIO.Salario =@salario_min;

SELECT *
FROM FUNCIONARIO 
WHERE FUNCIONARIO.Salario = @salario_min;
*/

SELECT COUNT (FUNCIONARIO.Cpf)
FROM FUNCIONARIO;

SELECT
(SELECT COUNT(*) FROM FUNCIONARIO)
+
(SELECT COUNT(*) FROM DEPENDENTE) 

AS Total;


SELECT AVG(FUNCIONARIO.Salario)
FROM FUNCIONARIO;

SELECT SUM(FUNCIONARIO.Salario)
FROM FUNCIONARIO;

SELECT *
FROM FUNCIONARIO
WHERE FUNCIONARIO.Datanasc LIKE '1972%'

SELECT *
FROM FUNCIONARIO
WHERE FUNCIONARIO.Salario IN (25000,30000) ORDER BY FUNCIONARIO.Salario;

SELECT * 
FROM FUNCIONARIO
INNER JOIN TRABALHA_EM ON TRABALHA_EM.Fcpf = FUNCIONARIO.Cpf 
INNER JOIN PROJETO ON PROJETO.Projnumero = TRABALHA_EM.Pnr
WHERE PROJETO.Projnumero in (2,3,10,20) 
and FUNCIONARIO.Pnome NOT LIKE 'Fernando'
and TRABALHA_EM.Horas LIKE 10.0 ORDER BY PROJETO.Projnome;

SELECT * 
FROM FUNCIONARIO
INNER JOIN TRABALHA_EM ON TRABALHA_EM.Fcpf = FUNCIONARIO.Cpf 
INNER JOIN PROJETO ON PROJETO.Projnumero = TRABALHA_EM.Pnr
WHERE PROJETO.Projnumero IN (SELECT Pnr FROM TRABALHA_EM WHERE Fcpf = '33344555587' )
and FUNCIONARIO.Pnome NOT LIKE 'Fernando'
and TRABALHA_EM.Horas IN (SELECT Horas FROM TRABALHA_EM WHERE Fcpf = '33344555587' ) 
ORDER BY PROJETO.Projnome;


--novas consultas aula 22/08

SELECT FUNCIONARIO.Pnome , FUNCIONARIO.Unome , funcionario.Endereco , DEPARTAMENTO.Dnome
from FUNCIONARIO
INNER JOIN DEPARTAMENTO ON FUNCIONARIO.Dnr = DEPARTAMENTO.Dnumero
WHERE DEPARTAMENTO.Dnome = 'Pesquisa';

SELECT FUNCIONARIO.Pnome , FUNCIONARIO.Unome , funcionario.Endereco , PROJETO.Projnome
from FUNCIONARIO
INNER JOIN TRABALHA_EM on TRABALHA_EM.Fcpf = FUNCIONARIO.Cpf
inner join PROJETO ON PROJETO.Projnumero = TRABALHA_EM.Pnr
WHERE PROJETO.Projnome = 'ProdutoX';   

SELECT distinct projeto.Projlocal ,  PROJETO.Projnumero , DEPARTAMENTO.Dnumero , FUNCIONARIO.Unome , FUNCIONARIO.Endereco , FUNCIONARIO.Datanasc , DEPARTAMENTO.Data_inicio_gerente
FROM FUNCIONARIO
INNER JOIN DEPARTAMENTO ON FUNCIONARIO.Cpf = DEPARTAMENTO.Cpf_gerente
inner join TRABALHA_EM on FUNCIONARIO.Cpf = TRABALHA_EM.Fcpf
inner join PROJETO ON PROJETO.Projnumero = TRABALHA_EM.Pnr
WHERE PROJETO.Projlocal = 'Mauá';


SELECT F.Pnome AS 'F_NOME' , F.Unome  AS 'F_SOBRENOME' , S.Pnome AS 'Supervisor'
FROM FUNCIONARIO AS F
LEFT JOIN FUNCIONARIO AS S
ON F.Cpf_supervisor = S.Cpf;

SELECT *
FROM DEPARTAMENTO AS D
LEFT JOIN FUNCIONARIO AS F
ON F.Dnr = D.Dnumero
WHERE F.Cpf is null;

SELECT *
FROM funcionario AS F
LEFT JOIN DEPARTAMENTO AS D
ON F.Dnr = D.Dnumero
WHERE F.Dnr IS NULL;


SELECT *
FROM FUNCIONARIO AS F
RIGHT JOIN DEPARTAMENTO AS D
ON F.Dnr = D.Dnumero
WHERE F.Cpf is null;

SELECT *
FROM FUNCIONARIO AS F
FULL JOIN DEPARTAMENTO AS D
ON F.Dnr = D.Dnumero;

SELECT F.Pnome , F.Sexo, F.Datanasc
FROM FUNCIONARIO AS F
UNION
SELECT D.Nome_dependente , D.Sexo , D.Datanasc
FROM DEPENDENTE AS D

SELECT P.Projlocal
FROM PROJETO AS P
UNION 
SELECT LD.Dlocal
FROM LOCALIZACAO_DEP AS LD

SELECT P.Projlocal
FROM PROJETO AS P
UNION  ALL
SELECT LD.Dlocal
FROM LOCALIZACAO_DEP AS LD

SELECT FUNCIONARIO.Cpf
FROM FUNCIONARIO
EXCEPT
SELECT DEPARTAMENTO.Cpf_gerente
FROM DEPARTAMENTO

SELECT F.Pnome , F.Unome
FROM FUNCIONARIO AS F
WHERE F.Cpf 
IN(SELECT F.Cpf  
FROM FUNCIONARIO AS F
EXCEPT
SELECT S.Cpf_supervisor 
FROM FUNCIONARIO AS S)



SELECT F.Pnome , F.Unome
FROM FUNCIONARIO AS F
WHERE F.Cpf 
IN(SELECT F.Cpf  
FROM FUNCIONARIO AS F
INTERSECT
SELECT S.Cpf_supervisor 
FROM FUNCIONARIO AS S)

SELECT COUNT(F.Cpf) as 'Qts_Funcionarios'
FROM FUNCIONARIO AS F;

select COUNT(F.Cpf) AS 'NUMERO_FUNCIONARIOS' , D.Dnome
FROM FUNCIONARIO AS F
JOIN DEPARTAMENTO AS D
ON F.Dnr = D.Dnumero
GROUP BY D.Dnome;

select SUM(F.Salario) AS 'SOMA DOS SALARIOS' , D.Dnome
FROM FUNCIONARIO AS F
JOIN DEPARTAMENTO AS D
ON F.Dnr = D.Dnumero
GROUP BY D.Dnome;

SELECT AVG(TE.Horas) AS 'MEDIA DE HORAS' , P.Projnome
FROM TRABALHA_EM AS TE
JOIN PROJETO AS P
ON TE.Pnr = P.Projnumero
GROUP BY P.Projnome

SELECT COUNT(F.Cpf) as 'quantidade funcionarios' , f.Sexo
FROM FUNCIONARIO AS F
group by f.Sexo;

select MAX(F.Salario) AS 'SOMA DOS SALARIOS' , D.Dnome
FROM FUNCIONARIO AS F
JOIN DEPARTAMENTO AS D
ON F.Dnr = D.Dnumero
GROUP BY D.Dnome;


select COUNT(F.Cpf) AS 'NUMERO_FUNCIONARIOS' , D.Dnome
FROM FUNCIONARIO AS F
JOIN DEPARTAMENTO AS D
ON F.Dnr = D.Dnumero
GROUP BY D.Dnome 
HAVING COUNT(F.Cpf) > 3;


SELECT SUM(TE.Horas) AS 'HORAS' , P.Projnome
FROM TRABALHA_EM AS TE
JOIN PROJETO AS P
ON TE.Pnr = P.Projnumero
GROUP BY P.Projnome
HAVING SUM(TE.Horas) >= 50;

 
 SELECT F.Pnome , F.Cpf
 FROM FUNCIONARIO AS F
 WHERE EXISTS(SELECT 1 FROM DEPARTAMENTO AS D WHERE F.Cpf = D.Cpf_gerente)
 



